# Generated by Django 4.0.6 on 2022-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_listing_id_bids_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
